package com.mycompany.myapp;



import Gui.AjouterMatch;
import Gui.HomeForm;

import com.codename1.db.Database;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;

import java.text.ParseException;


import com.mycompagny.Service.UtilisateurServices;
import com.mycompany.gui.afficherequipeGUI;
import com.mycompany.Entite.DataBaseMobile;
import com.mycompany.Entite.Utilisateur;
import com.mycompany.gui.HomeAdminForm;

import com.mycompany.gui.Login;
import java.io.IOException;
/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication{

    private Form current;
    private static Resources theme;

     public static Database db;
boolean created =false;
boolean created2 =false;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    /**
     *
     * @throws ParseException
     */
   

    public void start() 
            //throws IOException 
    {
        
        
           created =Database.exists("dbRussia2018");
        try {
            db= Database.openOrCreate("dbRussia2018");
            if (created ==false)
            {
            
            db.execute("create table favoris (id int, usr int , eq int,  PRIMARY KEY (id,usr,eq));");
         
            }
            
            
        } catch (IOException ex) {
         
        }
<<<<<<< HEAD
       
=======
        created =Database.exists("dbRussia2018Ali");
        try {
            db= Database.openOrCreate("dbRussia2018Ali");
            if (created ==false)
            {
            
            db.execute("create table Utilisateurs (id int, username varchar , email varchar);");
            System.out.println("ok  ahahaha     ");
            }
            
        } catch (IOException ex) {
         
        }
>>>>>>> f1e82ea2183695dc7410467895976cd6e91cae5f
        
       if(current != null){
            current.show();
            return;
        }
   /*   afficherequipeGUI f;
        try {
            f = new afficherequipeGUI();
                    f.getF().show();

        } catch (IOException ex) {
        }*/
         


       Login l=new Login();
    // HomeAdminForm Admin = new HomeAdminForm();
    l.getF().show();

      // HomeAdminForm Admin = new HomeAdminForm();
      // Admin.getF().show();
    //    DataBaseMobile.Execute("insert into reclamation values(null,'1','1','2018-1-1','faza','faza okhra');");

    //  HomeForm h = new HomeForm();
    //   h.getF().show();

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }
 public void localNotificationReceived(String notificationId) {
                System.out.println("Received local notification "+notificationId);
            }

   
}
